#!/usr/bin/env lua

---@class (exact) Table
---@field size [number, number]
---@field ccol number
---@field crow number
---@field data number[][]
local Table = {}

---@type Table[]
local tables = {}
---@type number
local current_table = nil

---@alias Object string

---@param obj Object
---@param rstart number
---@param rend number
function NewRange(obj, rstart, rend)
  if obj == "table" then
    assert("TODO")
  elseif obj == "col" then
    TableResize(tables[current_table], rend-rstart+1, tables[current_table].size[1])
    local col = tables[current_table].ccol
    for i=1,rend-rstart+1 do
      tables[current_table].data[i][col] = rstart+i-1
    end
  elseif obj == "row" then
    TableResize(tables[current_table], tables[current_table].size[2], rend-rstart+1)
    local row = tables[current_table].crow
    for i=1,rend-rstart+1 do
      tables[current_table].data[row][i] = rstart+i-1
    end
  end
end

---@param obj Object
---@param f function 
function NewFunc(obj, f)
  if obj == "table" then
    assert("TODO")
  elseif obj == "col" then
    local col = tables[current_table].ccol
    for i=1,tables[current_table].size[2] do
      tables[current_table].data[i][col] = f(i, col, tables[current_table], tables, current_table)
    end
  elseif obj == "row" then
    local row = tables[current_table].crow
    for i=1,tables[current_table].size[1] do
      tables[current_table].data[row][i] = f(row, i, tables[current_table], tables, current_table)
    end
  end
end

---@param obj Object
---@param args number[]
function NewList(obj, args)
 if obj == "table" then
    assert("TODO")
  elseif obj == "col" then
    TableResize(tables[current_table], #args, tables[current_table].size[1])
    local col = tables[current_table].ccol
    for i=1,#args do
      tables[current_table].data[i][col] = args[i]
    end
  elseif obj == "row" then
    TableResize(tables[current_table], tables[current_table].size[2], #args)
    local row = tables[current_table].crow
    for i=1,#args do
      tables[current_table].data[row][i] = args[i]
    end
  end
end

---@param t Table
function TablePrint(t)
  io.write(string.format("table #%d (%dx%d)\n", current_table, t.size[1], t.size[2]))
  for _,r in pairs(t.data) do
    for _,c in pairs(r) do
      io.write(c)
      io.write(" ")
    end
    print()
  end
end

---@param t Table
---@param rows number
---@param cols number
function TableResize(t, rows, cols)
  t.size[1] = math.max(cols, t.size[1])
  t.size[2] = math.max(rows, t.size[2])
  for i=1,t.size[2] do
    t.data[i] = t.data[i] or {}
    for j=1,t.size[1] do
      t.data[i][j] = t.data[i][j] or 0
    end
  end
end

local errNoTable = "[ERROR] no table"
local errRangeArgs = "[ERROR] unvalid args for range"

---@param obj Object
function Fill(obj, ...)
  if obj == "table" then assert("TODO") end
  if not (obj == "table" or obj == "row" or obj == "col") then print("[ERROR] unknown obj") return end
  local args = {...}
  if args[1] == "range" then
    if #args < 3 then print(errRangeArgs) return end
    local rstart = tonumber(args[2])
    local rend = tonumber(args[3])
    if rstart == nil then print(errRangeArgs) return end
    if rend == nil then print(errRangeArgs) return end
    if rstart > rend then print(errRangeArgs) return end

    NewRange(obj, rstart, rend)
  elseif args[1] == "func" then
    if #args == 1 then print("[ERROR] expected argument for func") return end
    local func = args[2]
    for i,w in pairs(args) do
      if i > 2 then
        func = func .. " " .. w
      end
    end
    func = "return function(row, col, tab, tables, current_table) " .. func .. " end"
    local _f,err = load(func)
    if not _f then print("[ERROR] compiling function " .. func) print(err) return end
    local ok, f = pcall(_f)
    if ok then
      NewFunc(obj, f)
    else
      print("[ERROR] running function" .. func)
      print(f)
    end
  elseif args[1] == "list" then
   local _args = {}
    for i,e in ipairs(args) do
      if i >= 2 then
        local _e = tonumber(e)
        if not _e then print("[ERROR] expected number in list") return end
        table.insert(_args, _e)
      end
    end

    NewList(obj, _args)
  else
    print("[ERROR] unknown method")
  end
end

---@param obj Object
function New(obj, ...)
  local args = {...}
  if obj == "table" then
    table.insert(tables, {
      size = {0, 0},
      ccol = 0, crow = 0,
      data = {{}}
    })
    current_table = #tables
  elseif obj == "col" then
    if current_table == nil then print(errNoTable) return end
    TableResize(tables[current_table], tables[current_table].size[2], 1+tables[current_table].size[1])
    tables[current_table].ccol = tables[current_table].size[1]

    if #args > 0 then Fill(obj, ...) end
  elseif obj == "row" then
    if current_table == nil then print(errNoTable) return end
    TableResize(tables[current_table], 1+tables[current_table].size[2], tables[current_table].size[1])
    tables[current_table].ccol = tables[current_table].size[1]

    if #args > 0 then Fill(obj, ...) end
  end
end

---@param obj Object
---@param _num string
function Select(obj, _num)
  local num = tonumber(_num)
  if num == nil then print("[ERROR] unvalid num") return end

  if obj == "table" then
    if num >= #tables or num < 1 then print("[ERROR] unvalid num") return end
    current_table = num
  elseif obj == "col" then
    if num >= tables[current_table].size[1] or num < 1 then print("[ERROR] unvalid num") return end
    tables[current_table].ccol = num
  elseif obj == "row" then
    if num >= tables[current_table].size[2] or num < 1 then print("[ERROR] unvalid num") return end
    tables[current_table].crow = num
  else
    print("[ERROR] unknown obj")
  end
end

function Show()
  if current_table == nil then print(errNoTable) return end
  TablePrint(tables[current_table])
end

local help = [[
Comands:
q | quit | exit   quit
h | help | ?      print help
d | debug         toggle debug info
]]

---@param str string
---@return string,string
function Tokenize(str)
  local c = str:sub(1, 1)
  local i = 2
  local len = str:len()
  if c == ' ' then
    return Tokenize(str:sub(2, -1))
  elseif c == '"' then
    while i <= len and str:sub(i, i) ~= '"' do
      i = i + 1
    end
    return str:sub(1, i), str:sub(i+1, -1)
  else
    while i <= len and str:sub(i, i) ~= ' ' do
      i = i + 1
    end
    return str:sub(1, i-1), str:sub(i, -1)
  end
end

---@type boolean
local debug_enable = false

while true do
  io.write("> ")
  local input = io.read()

  local tokens, token = {}, nil
  token, input = Tokenize(input)
  while input ~= "" do
    table.insert(tokens, token)
    token, input = Tokenize(input)
  end
  if token ~= "" then
    table.insert(tokens, token)
  end

  if tokens[1] == "q" or tokens[1] == "quit" or tokens[1] == "exit" then
    break
  elseif tokens[1] == "help" or tokens[1] == "h" or tokens[1] == "?" then
    io.write(help)
  elseif tokens[1] == "debug" or tokens[1] == "d" then
    if debug_enable then
      debug_enable = false
    else
      debug_enable = true
    end
  elseif #tokens > 0 then
    local func = ""
    for i,w in ipairs(tokens) do
      if i == 1 then
        func = w:gsub("^%l", string.upper) .. "("
      elseif i == 2 then
        if w:sub(1,1) ~= '"' then
          func = func .. "\"" .. w .. "\""
        else
          func = func .. w
        end
      else
        if w:sub(1,1) ~= '"' then
          func = func .. ", \"" .. w .. "\""
        else
          func = func .. ", " .. w
        end
      end
    end
    func = func .. ")"
    if debug_enable then print("[INFO] running " .. func) end
    local f,cerr = load(func)
    if f == nil then print("[ERROR] cannot compile " .. func) print(cerr) break end
    local ok,err = pcall(f)
    if not ok then
      print("[ERROR] cannot run " .. func)
      print(err)
    end
  end
end
